CREATE TABLE `posts` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `link` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `posts` (`id`, `title`, `content`, `link`) VALUES
(1, 'Online Poll and Voting System with jQuery AJAX', 'The poll system used by the site administrator to get the users views on the topic or a product. The user can select an option and submit a vote. The overall percentage of the option will display after submit.', 'http://makitweb.com/online-poll-and-voting-system-with-jquery-ajax/'),
(2, 'How to Create custom Shortcode in WordPress', 'In WordPress, Shortcode is special tags which specified within the [] brackets and use on the page, post, and widget. The code is replaced with some other content when previewing the page. It can also take parameters. Shortcode is flexible and allows you to place it wherever you want.', 'http://makitweb.com/how-to-create-custom-shortcode-in-wordpress/'),
(3, 'How to Auto-populate Dropdown with AngularJS and PHP', 'By creating dynamic dependent dropdown the user is restricted to select an item to view data on another dropdown element. Based on each selection data is changed in the dropdown. The common example of this – country and state element in the form. According to the selected country state is been auto-populated.', 'http://makitweb.com/how-to-auto-populate-dropdown-with-angularjs-and-php/'),
(4, 'Pagination with Search Filter in CodeIgniter', 'Pagination gets complicated when to find specific groups of records when there is a large number of records are available.\n\nBy adding a search filter with pagination makes easier for the user to easily find records e.g. filter list by country, department, name etc.\n\nIt is easier to add pagination using pagination library in CodeIgniter.', 'http://makitweb.com/pagination-with-search-filter-in-codeigniter/'),
(5, 'Check uncheck All Checkboxes with Vue.js', 'Checkboxes are used on the page to allow the user to select multiple items from the list.\n\nIf the user wants to select all items then it needs to check all checkboxes one by one.\n\nTo make the selection process easier by adding a single checkbox and use it for check uncheck all checkboxes.', 'http://makitweb.com/check-uncheck-all-checkboxes-with-vue-js/'),
(6, 'How to Toggle CSS Classes and Styles with Vue.js', 'Sometimes it is required to control the flow of the CSS classes and style properties of the element based on the expression at runtime.\n\nIn Vue.js there is a v-bind directive to update the HTML attribute.\n\nIn this tutorial, I am using this on class v-bind:class and style v-bind:style.', 'http://makitweb.com/how-to-toggle-css-classes-and-styles-with-vue-js/'),
(7, 'How to Add Speech Recognition to the Website - JavaScript', 'With the use of Speech Recognition API, you can enable the web browser to take speech input on the page and convert it into text.\n\nFor accessing this on the page need to allow microphone access by the user.\n\nIn this tutorial, I am creating an example where allowing the users to search posts by speech. On the basis of speech recognition display response on the screen using jQuery AJAX.', 'http://makitweb.com/how-to-add-speech-recognition-to-the-website-javascript/'),
(8, 'How to Create and Load Model in CodeIgniter', 'In CodeIgniter Model are the PHP classes where all database related manipulation is done e.g. fetching records, insert, update, and delete records.\n\nWithin this, all data processing logic is done.\n\nAll model files are managed in application/models directory and they are load and access by the controller.', 'http://makitweb.com/how-to-create-and-load-model-in-codeigniter/'),
(9, 'Delete Multiple Selected Records with PHP', 'It is time-consuming to delete records one by one from the list.\n\nTo make deletion process easier for the users by allowing them to select multiple records using checkboxes.\n\nExecute delete query according to the selected checkboxes.', 'http://makitweb.com/delete-multiple-selected-records-with-php/'),
(10, 'Live username Availability check with AngularJS in CodeIgniter', 'If there is the registration form on the website then you need to make sure that the username or email must be unique.\n\nThe user will login with the selected username next time when it comes to the website.\n\nYou can either check it after submitting the form or while entering it.', 'http://makitweb.com/live-username-availability-check-with-angularjs-in-codeigniter/'),
(11, 'Bootstrap Datepicker Start and End date Validation', 'You can easily enable date selection to the form element using Bootstrap datepicker if you are already using Bootstrap in your page.\n\nYou need to add external Bootstrap datepicker library.\n\nThis allows the users to select any from the datepicker and they are not restricted.', 'http://makitweb.com/bootstrap-datepicker-start-and-end-date-validation/'),
(12, 'Remove Duplicate values from an Array in PHP', 'The array_unique() method is used to remove repeated or duplicate values from the array and return an array.\n\nIt is better to use this method on the array if there is some possibility of same values or the later code in the program depends on it for example – selecting records based on ids and displaying on the screen.', 'http://makitweb.com/remove-duplicate-values-from-an-array-in-php/'),
(13, 'Add Browse Button and Upload File in TinyMCE', 'In TinyMCE editor to view image and media options in the menu or in toolbar need to load them by using plugins option while initializing.\n\nThis adds them to the editor but you can load external file by passing the source path. It does not allow to browse any file within the system.\n\nThe browse button easily added by defining file_picker_callback option.', 'http://makitweb.com/add-browse-button-and-upload-file-tinymce/'),
(14, 'How to Get Records from Database with AngularJS in CodeIgniter', 'Data selection is required either to display information on the screen or use it for some data manipulation.\n\nIf you want to get records from the MySQL database using AngularJS in CodeIgniter then you need to create a method in the controller for handling the requests and return response.', 'http://makitweb.com/how-to-get-records-from-database-with-angularjs-in-codeigniter/'),
(15, 'Connect with Multiple Databases in CodeIgniter', 'A database is one of common requirement while building the dynamic application.\n\nIt uses to store related data in an organized manner.\n\nYou can use more than one database in your application.\n\nIf you are using CodeIgniter Framework then you need to define the database connection details separately for multiple databases and load it explicitly for performing operations on the database.', 'http://makitweb.com/connect-with-multiple-databases-in-codeigniter/');